spring:
#  flyway:
#    locations:
#      - classpath:db/migration
#      - classpath:db/migration-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/cityEvents
    username: postgres
    password: jocofinki246
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082